### ISSUE TITLE
invite

### ISSUE THREAD

**Issue by t1st3** [t1st3/is-7z#1]
@kevva, since you already own most of the Node.js modules that detect archives and/or compressed files, maybe you'd want to co-own this one that detects 7z files. Thanks in advance for your answer.

**Comment by kevva** [comment]
Sure, but isn't this similar to https://github.com/kevva/is-7zip?

**Comment by t1st3** [comment]
Wow, it's kind of exactly the same, but I feel even more stupid since I starred it some time ago!
